from .settings import (
    BUCKET_NAME,
    CHUNK_OVERLAP,
    CHUNK_SIZE,
    HUGGINGFACE_KEY,
    INDEX_NAME,
    LLM_KEY,
    SUPABASE_KEY,
    PINECONE_KEY,
    SUPABASE_TABLE,
    SUPABASE_URL,
)
