import os

from dotenv import load_dotenv

load_dotenv()

# constants
# str
BUCKET_NAME = "files"
INDEX_NAME = "smart-support"
SUPABASE_TABLE = "documents"

# int
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100
DIMENSION = 1024
TIMEOUT = 30

# keys
HUGGINGFACE_KEY = os.getenv("HUGGINGFACE_KEY")
LLM_KEY = os.getenv("LLM_KEY")
PINECONE_KEY = os.getenv("PINECONE_KEY")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

# URLS
CHAT_COMPLETIONS_URL = os.getenv("CHAT_COMPLETIONS_URL")
MULTILINGUAL_E5_EMBEDDER_URL = os.getenv("MULTILINGUAL_E5_EMBEDDER_URL")
MULTILINGUAL_MINILM_L12_CLASSIFICATION_URL = os.getenv(
    "MULTILINGUAL_MINILM_L12_CLASSIFICATION_URL"
)
SUPABASE_URL = os.getenv("SUPABASE_URL")

HEADERS = {
    "Authorization": f"Bearer {HUGGINGFACE_KEY}",
}
